debug:
  config: true

schedule:
  default:
  - '02:00 10'
  - '16:00 6'
  - '18:00 4'
  - '00:00 8'

  Sun:
  - '00:00 8'
  - '02:00 10'
  - '08:00 8'
  - '10:00 6'
  - '12:00 4'
  - '22:00 6'

worlds:
- world
- world_nether
